### ISSUE TITLE
Error building

### ISSUE THREAD

**Issue by AShortcuts** [flows-network/telegram-gpt#5]
I tried deploying this today and I added the openai api key and bot token, but I am getting a deployment error after "Updating crates.io index". Please advise

**Comment by juntao** [comment]
What is the exact error message? Perhaps a screenshot? Thanks.

**Comment by AShortcuts** [comment]
<img width="661" alt="optim_2024-03-31_634" src="https://github.com/flows-network/telegram-gpt/assets/47438100/44227ec9-a139-495c-bc66-f4c2930b892b">

**Comment by DarumaDocker** [comment]
Scroll to the bottom then you can see the error log.

**Comment by AShortcuts** [comment]
Ah. I copied the bottom-most parts where it seemed the errors began. Here you go:

Compiling telegram-gpt v0.1.0 (/reactor/func_repo/AShortcuts/Telegram-ChatGPT)
error: expected one of `(`, `.`, `::`, `;`, `?`, `}`, or an operator, found `:`
  --> src/lib.rs:35:17
   |
35 |         co.model: ChatModel::GPT35Turbo;
   |                 ^ expected one of 7 possible tokens

error: custom attribute panicked
  --> src/lib.rs:17:1
   |
17 | #[update_handler]
   | ^^^^^^^^^^^^^^^^^
   |
   = help: message: called `Result::unwrap()` on an `Err` value: Error("unexpected token, expected `;`")

warning: unused import: `serde_json::json`
 --> src/lib.rs:1:5
  |
1 | use serde_json::json;
  |     ^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused imports: `Telegram`, `UpdateKind`, `Update`
 --> src/lib.rs:2:34
  |
2 | use tg_flows::{listen_to_update, Telegram, Update, UpdateKind, update_handler};
  |                                  ^^^^^^^^  ^^^^^^  ^^^^^^^^^^

warning: unused imports: `ChatModel`, `ChatOptions`, `OpenAIFlows`
 --> src/lib.rs:4:12
  |
4 |     chat::{ChatModel, ChatOptions},
  |            ^^^^^^^^^  ^^^^^^^^^^^
5 |     OpenAIFlows,
  |     ^^^^^^^^^^^

warning: unused imports: `get`, `set`
 --> src/lib.rs:7:19
  |
7 | use store_flows::{get, set};
  |                   ^^^  ^^^

warning: unused import: `flowsnet_platform_sdk::logger`
 --> src/lib.rs:8:5
  |
8 | use flowsnet_platform_sdk::logger;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: `telegram-gpt` (lib) generated 5 warnings
error: could not compile `telegram-gpt` (lib) due to 2 previous errors; 5 warnings emitted
Function build returned with code 101

**Comment by DarumaDocker** [comment]
There is something wrong in your code. In fact, you can check it on your local machine by running `cargo check --target wasm32-wasi'

You may need to install target by running 'rustup target add wasm32-wasi`

**Comment by DarumaDocker** [comment]
I found this to be a bug  in our source code.
Fixed, please try again.
Sorry for the confusion.

**Comment by AShortcuts** [comment]
How would I update the code in my github repository?

**Comment by DarumaDocker** [comment]
Follow this answer: https://stackoverflow.com/a/56577320
If you are new to git cli, you can delete your old repo and recreate it from scratch on flows.network

**Comment by AShortcuts** [comment]
Thank you very much. I deleted the old repository and recreated it and everything is now running smoothly 👍.
